version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: flowforge-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: flowforge123
      MONGO_INITDB_DATABASE: flowforge
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: flowforge-backend
    restart: always
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:flowforge123@mongodb:27017/flowforge?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: flowforge-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: